apiVersion: v1
kind: Service
metadata:
  labels:
    name: registry
  name: registry-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: web-registry
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    name: registry
  deprecatedPublicIPs:
  - {{ kube_node1.ip }}
