kind: ReplicationController
apiVersion: v1
metadata:
  name: registry-rc
  labels:
    name: registry-rc
spec:
  replicas: {{ registry_replicas }}
  selector:
    name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
      - name: registry
        image: docker.io/registry:2
        volumeMounts:
        - mountPath: "/var/certs:z"
          name: certdir
        env:
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /var/certs/domain.crt
          - name: REGISTRY_HTTP_TLS_KEY
            value: /var/certs/domain.key
        ports:
          - name: reg-port
            containerPort: {{ registry_port }}
      volumes:
        - name: certdir
          hostPath:
            path: "/var/certs"
